-- Backend-only data. Supabase anon/authenticated roles receive no table policies.
-- Prisma connects using the privileged server database role.
ALTER TABLE "HiveSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveWorkspace" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveProject" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveTest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveTestVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveSecret" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveRunStep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveArtifact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveUsage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveNotification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveDeployment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveBillingEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "HiveAudit" ENABLE ROW LEVEL SECURITY;
